login:
  path: /api/login

#home:
#  path: /
#  controller: App\Controller\HomeController::index

index:
  path: /*
  controller: App\Controller\HomeController::index
#  requirements:
#    wildcard: *
